ALTER TABLE KF_SYSTEM.T00016_CSV_PROGRESS
 DROP PRIMARY KEY CASCADE;

DROP TABLE KF_SYSTEM.T00016_CSV_PROGRESS CASCADE CONSTRAINTS;

CREATE TABLE KF_SYSTEM.T00016_CSV_PROGRESS
(
  ID            NUMBER,
  APEX_SESSION  NUMBER,
  USERNAME      VARCHAR2(255 BYTE),
  STAGE         VARCHAR2(10 BYTE),
  MESSAGE       VARCHAR2(255 BYTE),
  COMPLETE      NUMBER,
  CURR          NUMBER,
  SEQ           NUMBER,
  ERR           NUMBER,
  ERRM          VARCHAR2(1000 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX KF_SYSTEM.T00016_CSV_PROGRESS_PK ON KF_SYSTEM.T00016_CSV_PROGRESS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER KF_SYSTEM."BI_T00016_CSV_PROGRESS" 
   
before insert ON KF_SYSTEM.T00016_CSV_PROGRESS               
  for each row
begin   
  if :new."ID" is null then 
    select "S00016_CSV_PROGRESS_SEQ".nextval into :new."ID" from dual; 
  end if; 
end;
/


ALTER TABLE KF_SYSTEM.T00016_CSV_PROGRESS ADD (
  CONSTRAINT T00016_CSV_PROGRESS_PK
  PRIMARY KEY
  (ID)
  USING INDEX KF_SYSTEM.T00016_CSV_PROGRESS_PK
  ENABLE VALIDATE);

GRANT SELECT ON KF_SYSTEM.T00016_CSV_PROGRESS TO OPERATION_APEX_001;
