DROP TABLE KF_SYSTEM.T00007_PSI_EXC_TABLE CASCADE CONSTRAINTS;

CREATE TABLE KF_SYSTEM.T00007_PSI_EXC_TABLE
(
  LOG_SEQUENCE       NUMBER,
  EXCEPTION_NUMBER   NUMBER,
  EXCEPTION_MESSAGE  VARCHAR2(400 BYTE),
  EXCEPTION_STACK    VARCHAR2(2000 BYTE),
  CALL_STACK         VARCHAR2(2000 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON KF_SYSTEM.T00007_PSI_EXC_TABLE TO KFM_FICHE;
