ALTER TABLE KF_SYSTEM.T00009_PSI_PARAMETER_TABLE
 DROP PRIMARY KEY CASCADE;

DROP TABLE KF_SYSTEM.T00009_PSI_PARAMETER_TABLE CASCADE CONSTRAINTS;

CREATE TABLE KF_SYSTEM.T00009_PSI_PARAMETER_TABLE
(
  PARAM_NAME   VARCHAR2(20 BYTE),
  PARAM_VALUE  VARCHAR2(80 BYTE),
  PARAM_DESC   VARCHAR2(200 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX KF_SYSTEM.T00009_PSI_PARAMETER_TABLE_PK ON KF_SYSTEM.T00009_PSI_PARAMETER_TABLE
(PARAM_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE KF_SYSTEM.T00009_PSI_PARAMETER_TABLE ADD (
  CONSTRAINT T00009_PSI_PARAMETER_TABLE_PK
  PRIMARY KEY
  (PARAM_NAME)
  USING INDEX KF_SYSTEM.T00009_PSI_PARAMETER_TABLE_PK
  ENABLE VALIDATE);

GRANT SELECT ON KF_SYSTEM.T00009_PSI_PARAMETER_TABLE TO KF_SYSTEM_APEX_001;
