DROP TABLE KF_SYSTEM.T00008_PSI_LOG_TABLE CASCADE CONSTRAINTS;

CREATE TABLE KF_SYSTEM.T00008_PSI_LOG_TABLE
(
  LOG_SEQUENCE  NUMBER,
  CREATE_DATE   DATE,
  CATEGORY      CHAR(1 BYTE),
  LOG_LEVEL     NUMBER,
  MESSAGE       VARCHAR2(800 BYTE)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


GRANT SELECT ON KF_SYSTEM.T00008_PSI_LOG_TABLE TO ENVIRONMENT;

GRANT SELECT ON KF_SYSTEM.T00008_PSI_LOG_TABLE TO KFM_FICHE;
