ALTER TABLE KF_SYSTEM.T00016_CSV_FILES
 DROP PRIMARY KEY CASCADE;

DROP TABLE KF_SYSTEM.T00016_CSV_FILES CASCADE CONSTRAINTS;

CREATE TABLE KF_SYSTEM.T00016_CSV_FILES
(
  ID             NUMBER,
  APP_ID         VARCHAR2(30 BYTE),
  APEX_SESSION   NUMBER,
  APEX_USER      VARCHAR2(255 BYTE),
  FILENAME       VARCHAR2(255 BYTE),
  DATE_UPLOADED  DATE,
  FILE_BLOB      BLOB
)
LOB (FILE_BLOB) STORE AS (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          64K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                  FLASH_CACHE      DEFAULT
                  CELL_FLASH_CACHE DEFAULT
                 ))
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX KF_SYSTEM.T00016_CSV_PK ON KF_SYSTEM.T00016_CSV_FILES
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER KF_SYSTEM."T00016_CSV_PK_LOAD" 
   
  before insert ON KF_SYSTEM.T00016_CSV_FILES               
  for each row
begin   

  if :new."ID" is null then 
    select "S00016_CSV_FILES_SEQ".nextval into :new."ID" from dual; 
  end if; 

end;
/


ALTER TABLE KF_SYSTEM.T00016_CSV_FILES ADD (
  CONSTRAINT T00016_CSV_PK
  PRIMARY KEY
  (ID)
  USING INDEX KF_SYSTEM.T00016_CSV_PK
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON KF_SYSTEM.T00016_CSV_FILES TO OPERATION_APEX_001;

GRANT DELETE, INSERT, SELECT, UPDATE ON KF_SYSTEM.T00016_CSV_FILES TO OPERATION_DATA;
